import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container1: {
      flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#F3F6FA',
    padding: 20,
  },
  card: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 32,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
    alignItems: 'stretch',
  },
  tituloCardRegistro: {
    fontSize: 22,
    fontWeight: '700',
    color: '#102F50',
    textAlign: 'center',
    marginTop: 15,
  },
  title: {
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 20,
    fontWeight: '600',
    color: '#102F50',
    marginBottom: 8,
    marginTop: 35,
  },
  titleIcon: {
    marginRight: 8,
    fontSize: 20,
  },
  input: {
    width: '90%',
    borderWidth: 0,
    backgroundColor: '#F6F8FA',
    padding: 16,
    borderRadius: 16,
    marginBottom: 15,
    fontSize: 18,
    color: '#102F50',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  pickerContainer: {
    width: '90%',
    borderWidth: 0,
    borderRadius: 16,
    backgroundColor: '#F6F8FA',
    marginBottom: 15,
    paddingHorizontal: 0,
    paddingVertical: 0,
    minHeight: 48, 
    justifyContent: 'center',
  },
  dateButton: {
    width: '90%',
    padding: 16,
    backgroundColor: '#F6F8FA',
    borderRadius: 16,
    alignItems: 'flex-start',
    marginBottom: 15,
    borderWidth: 0,
  },
  dateText: {
    color: '#102F50',
    fontSize: 18,
    opacity: 0.7,
  },
  buttonContainer: {
    marginTop: 18,
    alignItems: 'center',
  },
  salvarBotao: {
    marginTop: 30,
    backgroundColor: 'rgb(9, 79, 136)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: 350,
  },
  textoBotao: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },

  cardGlicemia: {
    backgroundColor: 'rgb(249, 253, 250)',
    padding: 20,
    width: 350,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 35,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardValor: {
    fontSize: 30,
    fontWeight: '700',
    color: '#1A3666',
    textAlign: 'center',
  },
  cardTexto: {
    marginTop: 8,
    fontSize: 18,
    color: '#0E77CC',
    textAlign: 'center',
  },

  iconeGlicemia: {
    fontSize: 34,
    marginBottom: 10,
  },
});
