import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    contentContainer: {
    paddingBottom: 24,
    flexGrow: 1,
    flex: 1,
    backgroundColor: '#F7F7F7', //f0f4fa
    paddingTop: 0,
    paddingRight: 20,
    paddingLeft: 20,
    justifyContent: 'space-between',
  },
  content: {
    width: '100%',
    padding: 5,
    marginTop: 10,
    marginBottom: 10,
    alignItems: 'center',
    flexDirection: 'row',
  },
  logo: {
    width: 37,
    height: 37,
  },
  boasVindas: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1C3D73',
    marginBottom: 20,
    textAlign: 'center'
  },
  alerta: {
    fontSize: 15,
    color: '#FF4D4F',
    marginTop: 10,
    fontWeight: '600',
  },
  gridAcoes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  cardBotao: {
    width: '48%',
    height: 116,
    backgroundColor: 'rgba(9, 79, 136, 0.1)',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
    flexDirection: 'row'
  },
  textoCard: {
    fontSize: 14,
    color: '#1C3D73',
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 6,
  },
  textoIcon: {
    fontSize: 25,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(9, 79, 136, 0.08)',
    marginLeft: -20,
    marginRight: -20,
    paddingTop: 5,
  },
  textoBotaoPequeno: {
    fontSize: 14,
    color: '#1C3D73',
    fontWeight: '500',
    letterSpacing: 0.3,
    textAlign: 'center',
    marginTop: 5,
  },
  imageIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontSize: 25,
  },
  botaoPequeno: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselCard: {
    borderRadius: 28,
    padding: 0,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: 320,
    height: 200,
  },
  carouselIcon: {
    fontSize: 32,
  },
  carouselTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 8,
    color: '#1C3D73',
  },
  carouselDescription: {
    fontSize: 15,
    color: '#1C3D73',
    marginTop: 6,
    textAlign: 'center',
  },
  iconeContainer1: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
},
  carouselFrase: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    color: '#1C3D73',
    lineHeight: 20,
    padding: 15,
  },
  cardSecundario: {
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E3E6FA',
    padding: 20,
    marginBottom: 12,
     width: '100%',
     height: 170,
     justifyContent: 'center',
     alignItems: 'flex-start'
  },
  cardTitulo: {
    fontSize: 17,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#2C3166',
},
  cardTexto: {
    fontSize: 16,
    color: '#2C3166',
    marginBottom: 2,
},
  cardValorPrincipal: {
    fontSize: 38,
    fontWeight: 'bold',
    color: '#2C3166',
    marginBottom: 2,
},
  logoCard: {
    width: 25,
    height: 25,
  },
  iconeContainer: {
    padding: 10,
    marginRight: 7, 
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
},
});
