import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container1: {
      flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingTop: 0,
    backgroundColor: '#F7FAFE',
  },
  card: {
    width: '90%',
    maxWidth: 520,
    backgroundColor: '#fff',
    borderRadius: 32,
    padding: 36,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
    alignItems: 'stretch',
    marginBottom: 30,
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3166',
    marginTop: 35,
    marginBottom: 16,
    textAlign: 'center',
  },
  subtitulo: {
    fontSize: 16,
    color: 'rgba(16, 47, 80, 0.73)',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 12,
  },
  input: {
    height: 48,
    width: '95%',
    borderWidth: 1,
    borderColor: '#E3E6FA',
    backgroundColor: '#F8FAFF',
    paddingHorizontal: 16,
    fontSize: 20,
    color: '#22304A',
    marginBottom: 22,
    borderRadius: 12,
  },
  label: {
    fontSize: 18,
    fontWeight: '600',
    color: '#22304A',
    marginBottom: 6,
    marginLeft: 2,
  },
  linha: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 18,
  },
  coluna: {
    flex: 1,
  },
  botaoEditar: {
    marginTop: 30,
    backgroundColor: '#7AA2C2',
    paddingVertical: 14,
    borderRadius: 17,
    alignItems: 'center',
    width: '100%',
  },
  botaoSalvar: {
    marginTop: 30,
    backgroundColor: 'rgb(9, 79, 136)',
    paddingVertical: 13,
    borderRadius: 15,
    alignItems: 'center',
    width: '100%',
  },
  textoBotao: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  abasContainer: {
    flexDirection: 'row',
    marginBottom: 18,
    width: '100%',
    backgroundColor: 'transparent',
    justifyContent: 'center',
  },
  aba: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  abaAtiva: {
    borderBottomColor: '#3E6481',
  },
  abaInativa: {
    borderBottomColor: 'transparent',
  },
  textoAba: {
    fontWeight: '600',
    fontSize: 19,
    color: '#22304A',
    marginTop: 20
  },
});
