import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container1: {
      flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#F3F6FA',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  card: {
    width: '95%',
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 4,
    alignItems: 'stretch',
    marginBottom: 30,
  },
  titulo: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 18,
    color: '#102F50',
    textAlign: 'center',
  },
  subtitulo: {
    fontSize: 17,
    marginBottom: 15,
    color: '#555',
    textAlign: 'center',
  },
  botoesPeriodo: {
    flexDirection: 'column',
    gap: 10,
    marginBottom: 30,
    alignItems: 'center',
  },
  botaoPeriodo: {
    backgroundColor: '#fff',
    borderWidth: 0,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  textoBotao: {
    color: '#102F50',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  textoBotao2: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  resumoContainer: {
    backgroundColor: '#E0F2F1',
    padding: 24,
    borderRadius: 18,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    width: '100%',
    alignItems: 'center',
  },
  resumoTitulo: {
    fontSize: 19,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#00796B',
    textAlign: 'center',
  },
  itemResumo: {
    fontSize: 17,
    marginBottom: 5,
    color: '#333',
    textAlign: 'center',
  },
  botaoExportar: {
    backgroundColor: 'rgb(9, 79, 136)',
    paddingVertical: 14,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    width: 320,
    alignSelf: 'center',
    shadowColor: '#3E6481',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  formularioPersonalizado: {
    marginBottom: 30,
    alignItems: 'center',
    width: '100%',
  },
  inputData: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#64B5F6',
    padding: 14,
    borderRadius: 14,
    marginBottom: 15,
    fontSize: 17,
    color: '#23405C',
    width: '95%',
  },
  erro: {
    color: 'red',
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
    textAlign: 'center',
  },
  label: {
    fontSize: 16,
    marginBottom: 10,
    color: '#555',
  },
  picker: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#64B5F6',
    borderRadius: 8,
    marginBottom: 20,
    paddingVertical: 10,
    paddingHorizontal: 15,
    fontSize: 16,
  },
  inputDataFocus: {
    borderColor: '#388E3C',
  },
  botaoExportarDisabled: {
    backgroundColor: '#BFD6E6',
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#F3F6FA',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 20,
  },
});
