import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container1: {
      flex: 1,
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F0F4F8',   
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: '#2A3E6D',
    marginVertical: 12,
  },
  picker: {
    width: '100%',
    minHeight: 40,
    borderWidth: 1,
    borderColor: '#A9C5E0',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    marginBottom: 20,
    justifyContent: 'center',
    color: '#2A3E6D',
  },
  input: {
    width: '100%',
    minHeight: 40,
    borderColor: '#A9C5E0',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    color: '#2A3E6D',
    marginBottom: 20,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderColor: '#D2D6DC',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2A3E6D',
  },
  counter: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#A9C5E0',
    borderRadius: 15,
    overflow: 'hidden',
  },
  counterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#FFFFFF',
  },
  counterIcon: {
    fontSize: 18,
    color: '#2A3E6D',
    fontWeight: '600',
  },
  counterValue: {
    minWidth: 24,
    textAlign: 'center',
    fontSize: 16,
    color: '#2A3E6D',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 24,
  },
  summaryCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  summaryIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2A3E6D',
  },
  summaryLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  buttonContainer: {
    marginTop: 32,
    borderRadius: 10,
    backgroundColor: 'rgb(9, 79, 136)',
    overflow: 'hidden',
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  textoBotaoSalvar: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    paddingHorizontal: 20,
  },
  selectListInput: {
    color: 'rgba(16, 47, 80, 0.88)',
    fontSize: 18,
  },
  selectListDropdown: {
    color: 'rgba(16, 47, 80, 0.62)',
    fontSize: 18,
  },
});
